# Generated by Django 4.1.7 on 2023-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvform',
            name='clz_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cvform',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cvform',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cvform',
            name='interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvform',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cvform',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cvform',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvform',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
