# Generated by Django 4.1.7 on 2023-03-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cvform_clz_name_cvform_date_created_cvform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvform',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cvform',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
