# Generated by Django 4.1.7 on 2023-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cvform_summary_alter_cvform_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvform',
            name='summary',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
